### ISSUE TITLE
Confusion about family string in 70-emojione-color.conf

### ISSUE THREAD

**Issue by ScottDWebster** [maximbaz/dotfiles#1]
Hello.  I am new to configuring fonts.  I fell down this rabbit hole trying to get nice emoji fonts working in Chrome on Linux.  I have been messing with varying versions of ~/.config/fontconfig/fonts.conf in trying different emoji fonts (Google's noto-emoji and a couple of versions of the EmojiOne fonts).
The "Linux Setup Help" section of https://github.com/emojione/emojione/tree/master/extras/fonts points to your 70-emojione-color.conf file.  I am confused as to why the family string is "Noto Color Emoji" instead of "EmojiOne" or "EmojiOne Color".  Doesn't that mean it will use the Google font instead of the EmojiOne font?

**Comment by ScottDWebster** [comment]
Ah!  I've just noticed that while emojione-svg.otf reports itself as "EmojiOne", emojione-android.ttf reports itself as "Noto Color Emoji".  That must be why you use that string.  It is quite strange that they've misnamed (or mislabeled) their own font.

**Comment by maximbaz** [comment]
Hello! That is exactly right, my `70-emojione-color.conf` is configured for `emojione-android.ttf` which reports itself as "Noto Color Emoji". 

There is a very good reason for why they named it like that, it is because the font is primarily targeted for Android devices (surprise-surprise), and the fact that it works on Linux is a pleasant side-effect. Now, Android devices do not have fontconfig where you can define a font name to use, instead it is hardcoded in there that the _only_ possibility for a valid emoji font is a ttf file called `/system/fonts/NotoColorEmoji.ttf` which reports itself as `Noto Color Emoji` - any other font is rejected as invalid. 

So, EmojiOne made their `emojione-android.ttf` font report itself as `Noto Color Emoji` for one reason, to make their instructions for Android users as simple as possible, namely: take `emojione-android.ttf` file and place it as `/system/fonts/NotoColorEmoji.ttf` on the device, and you are good to go, no other configuration needed. 

For Linux, it doesn't really matter how the font reports its name, as long as it is something unique. You have probably seen in my `70-emojione-color.conf` that I define a bunch of aliases for all known to me emoji fonts, all of which point to `Noto Color Emoji`. That way, I'm independent of a given font file (e.g. I can switch to any other emoji font by simply doing `s/Noto Color Emoji/Other Emoji Name/` and I'm also independent of application developers who sometimes hardcode emoji fonts to only some providers (e.g. I've personally seen websites that require `Noto Color Emoji` font and no other font to display emojis).

Hope that makes sense 🙂 Do you have any other questions, and more importantly, did you manage to configure color emojis on your system? 😃

**Comment by ScottDWebster** [comment]
Hi.  Thanks for the response.  I stayed up way too late last night messing with all of this.
When I saw that emojione-apple.ttf reported itself as "Apple Color Emoji" I realized why it and the android font were named the way they were. The downside of this is that there is a naming collision if you have the real google noto emoji font installed.

By the way, is renaming a file in ~/.config/fontconfig/conf.d to have an extension of "fnoc" instead of "conf" sufficient to prevent it from being loaded?  It seems like that is working.  I have your config and one from the EmojiOneColor-SVGinOT-Linux-1.3.tar.gz tarball stored there. I have a whole bunch of different configs (two of which are hard links to files in ~/.config/fontconfig/conf.d/) in ~/config/fontconfig/ and can switch between with something like "rm fonts.conf; ln -s AppleColorEmoji.conf fonts.conf; fc-cache -f -v".

Also, what do you use to test the rendering of emojis in a web page?  EmojiOne's page (http://eosrei.github.io/emojione-color-font/full-demo.html) doesn't seem to work well in Chrome (it shows black and white outline emojis in chrome but full color ones in Firefox) but http://www.istartedsomething.com/uploads/emojisegoe.html seems to work well.

I am using Fedora 25 and found that someone had made RPMS using openSUSE's build service apparently based on EmojiOneColor-SVGinOT-Linux-1.3.tar.gz although they din't include everything from the tarball (the fontconfig file is missing, for one).
I am currently using the emojione-apple.ttf font file and this simple fonts.conf:
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
	<match>
		<test name="family"><string>sans-serif</string></test>
			<edit name="family" mode="prepend" binding="weak">
				<string>Apple Color Emoji</string>
			</edit>
	</match>
	<match>
		<test name="family"><string>serif</string></test>
		<edit name="family" mode="prepend" binding="weak">
			<string>Apple Color Emoji</string>
		</edit>
	</match>
	<match>
		<test name="family"><string>Apple Color Emoji</string></test>
		<edit name="family" mode="prepend" binding="weak">
			<string>Apple Color Emoji</string>
		</edit>
	</match>
</fontconfig>`

It seems to be working well.  I tested your config a moment ago and find that (at least on my system) it causes a problem with digits disappearing (evident when viewing http://www.istartedsomething.com/uploads/emojisegoe.html).  I think that has to do with the binding strength.  I had found the solution of changing the binding to "weak" in the discussion on http://www.omgubuntu.co.uk/2016/08/enable-color-emoji-linux-google-chrome-noto

By the way, I have read that Google has done a way with the blob face emojis.  I haven't heard whether that is a redesign of the noto emoji font or if they have created a new font for Android Oreo.

**Comment by maximbaz** [comment]
Changing a file extension should be sufficient to ignore the config. Just so that you know, I found that I sometimes need to execute `fc-cache -f` both as my user and as a sudo, otherwise I see some weirdness, so I generally run `$ fc-cache -f; sudo fc-cache -f` at once.

This is how both pages are displayed in my Chromium:

![image](https://user-images.githubusercontent.com/1177900/29676499-8e990996-88f8-11e7-8307-bb186041208d.png)

![image](https://user-images.githubusercontent.com/1177900/29676573-b2f8f242-88f8-11e7-9ed5-bce0a6e902c4.png)

The way I was testing emojis when I was working on the fontconfig file is I was implementing an emoji autocomplete feature for [Wire app](https://wire.com), and I was naturally dealing a lot with emojis back then. I also learned how to write applications correctly so that they use emojis correctly. For example, the second demo page that you referenced has no spaces and all numbers are treated as emojis - this is the bug in their stylesheet:

![image](https://user-images.githubusercontent.com/1177900/29676787-5deb2bc0-88f9-11e7-81fb-b702cfd39955.png)

Changing the bindings to weak will maybe fix the issue, but it will cause other problems where other fonts will take precedence and true emoji will stop being rendered sometimes. I'll play with it again, but so far I haven't been able to apply the bindings to fix the issue without introducing more issues. There is a way though for the developers of that website to write stylesheet in a way that will work 100% correctly, with no changes to fontconfig required.

Although `emojione-apple.ttf` works, I'd recommend using the android version instead. For once, I have recently made an automated job to build `emojione-android.ttf` file, so it always stays up to date. The rest of the fonts require manual updates and thus always lag behind and depend on community to be upgraded. And looks like there is only one person in the world who knows how to compile apple font and who has been maintaining that font for the past few versions 🙂 But I also found some bugs in apple font, namely that the [emoji glyphs are not centered](https://github.com/emojione/emojione/issues/441) and that screws up the whole text alignment in all the apps - haven't heard of this issue being fixed, and android font doesn't suffer from it.

The new Google emoji font will be released soon, subscribe to this issue if you are interested: https://github.com/googlei18n/noto-emoji/issues/141. But looking at [their design](https://emojipedia.org/google/android-8.0/), I still prefer the EmojiOne 🙂

**Comment by ScottDWebster** [comment]
Would you consider publishing your EmojiOne android font build code?  I'm thinking there would be a way to modify the name before building to prevent name collisions.
Do you know if there is a way to control the precedence of the loading of fonts (system vs. ~/.local/share/fonts/)?  The system fonts seem to have precedence.
At the moment I am using the latest Noto emojis.  I only started looking at EmojiOne because I hated the blobs and they're finally gone.
I can't seem to get chrome or chromium to show color emojis.  I even upgraded to the latest chrome release.  Maybe your chromium is newer than that.

**Comment by maximbaz** [comment]
The build code is published as a Docker image: https://github.com/maximbaz/docker-emojione-fonts-build

It will show you all the dependencies needed to build the font. But primarily the building is done by the https://github.com/maximbaz/emojione-android project.

No, unfortunately I don't know how to control the precedence.

My Chromium is of version 60.0.3112.113. In case fontconfig version is also relevant, I currently have version 2.12.4 installed.

**Comment by ScottDWebster** [comment]
OK.  Thanks for your help.  I need to get other things done, but maybe I'll come back and take a crack at setting this up later.

**Comment by maximbaz** [comment]
All right :+1:

**Comment by maximbaz** [comment]
Hey, which OS are you using? I recently updated the `Linux Setup Help` section in the [EmojiOne repo](https://github.com/emojione/emojione/tree/master/extras/fonts).

For Arch Linux there is a [ttf-emojione package](https://aur.archlinux.org/packages/ttf-emojione/) now which does all the setup steps.

Most importantly, just make sure you remove all EmojiOne fonts from the system (in case you installed older SVGinOT or black-and-white from Adobe), and install the most recent `emojione-android.ttf` font from emojione-assets repo.

**Comment by Frodox** [comment]
I'm using [Mageia](https://www.mageia.org/). Ah, Ok, I will follow readme from EmojiOne repo then :ok_hand:
