### ISSUE TITLE
Few question about your arch installation.

### ISSUE THREAD

**Issue by thepenguinthatwants** [maximbaz/dotfiles#12]
Hi!

Looking at your setup it feels very complete. I've being using archlinux for a while but there are always things that are totally new and in a way I cant fiddle things out totally. So I wanted to ask few questions.

So I saw this line, does it mean you can add a optional key into a usb key? 
`cryptsetup luksAddKey /dev/sdX2 /crypto_keyfile.bin`
Is it then possible to make it password based login but also being able to login using keyfile. Like having multiple keys? 

Why did you use?
dbus-uuidgen --ensure
I've never done it before so wondering what does it do? Is it related to your btrfs setup? 

Have being using systemd-boot for a while but gotten quite envious about the snap-pac-grub so maybe changing back to grub cos of that. Or Do you know if it can be easily converted to systemd-boot?

**Comment by maximbaz** [comment]
Hey!

> So I saw this line, does it mean you can add a optional key into a usb key?
> `cryptsetup luksAddKey /dev/sdX2 /crypto_keyfile.bin`
> Is it then possible to make it password based login but also being able to login using keyfile. Like having multiple keys?

No no, this is for another purpose. Because my `/boot` is also encrypted, I am first asked for a password for GRUB, but then I'm asked _again_ for the same password to unlock the root partition. This trick simply allows to unlock the root partition automatically, without having to repeat the password. Check out [this wiki](https://wiki.archlinux.org/index.php/Dm-crypt/Encrypting_an_entire_system#Avoiding_having_to_enter_the_passphrase_twice) for more details.

> Why did you use?
> dbus-uuidgen --ensure
> I've never done it before so wondering what does it do? Is it related to your btrfs setup?

This ensures that a file `/var/lib/dbus/machine-id` exists and contains a UUID, I don't remember precisely, but some app required that file. Basically it's a machine ID.

> Have being using systemd-boot for a while but gotten quite envious about the snap-pac-grub so maybe changing back to grub cos of that. Or Do you know if it can be easily converted to systemd-boot?

My main reason to use GRUB was because AFAIK systemd-boot doesn't support encrypted `/boot`, but then yes `grub-btrfs` / `snap-pac-grub` also are made for GRUB, so I'm locked in with GRUB anyway 😄
