### ISSUE TITLE
icons workflow, taskbar ttf source

### ISSUE THREAD

**Issue by cyrinux** [maximbaz/dotfiles#2]
Hi Maxim, 
thanks you very much for your dot files, install guide. 
I use them and follow your work for my arch install.
-Could you please explain the workflow for get "PUA-A" font code? Must I use fontforge?
-What is the source of taskbar.ttf, is it a custom mixed fonts?

**Comment by maximbaz** [comment]
Hi, glad you found them useful!

`taskbar.ttf` is a custom font that I made myself in Font Forge, most of the icons are based on Font Awesome with some position / size modifications to look better on the py3status bar, but a few of them I made myself (like the "charging battery" icon) - I might have found an svg online to start with, but I don't remember to be honest.

To know which icon from taskbar.ttf belongs to which code point, the only option is to open the font with Font Forge. I've just recently moved all icons into to PUA-A section, at the moment there are icons in the range `F0000-F003B`. For your convenience:

![image](https://user-images.githubusercontent.com/1177900/35352212-86e96e84-0143-11e8-9d1c-2f201411ec33.png)

**Comment by cyrinux** [comment]
Ok great, this is what i was thinking! I have done yesterday the update in PUA-A, but I don't understand at all the difference and can't find good information about what i PUA-A, I must learn more about font I think.
I'm searching in fontforge where I can get this PUA-A code.
If you have a good documentation, sources about this...
Thanks yet !

**Comment by maximbaz** [comment]
Unicode has split the available codes into sections, and defined 3 areas as "Private Use Areas (PUA)" promising that these codes will never conflict with other fonts. These areas are therefore very useful to use for icon fonts, because you can stop worrying that your icon font may conflict with some other regular font.

Initially I was using using the first area, called [Basic Multilingual Plane](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane), but Font Awesome is using the same area for their icons, and I got into a conflict. That's why I moved all my icons in taskbar.ttf into the first supplementary area called [PUA-A](https://en.wikipedia.org/wiki/Plane_(Unicode)#Private_Use_Area_planes) and now I can use both Font Awesome and my taskbar fonts and they never conflict.

In Font Forge open taskbar.ttf and you can reach any area using the following two methods:

1. Menu > Element > Font Info > Unicode Ranges and click for example on "Supplementary Private Use Area-A":

![image](https://user-images.githubusercontent.com/1177900/35354134-7b690aaa-0149-11e8-9031-7cdc3b5e5b01.png)

2. Learn the code yourself (e.g. PUA-A starts with `F0000`), click Menu > View > Go to > type `uF0000` and hit Enter.

![image](https://user-images.githubusercontent.com/1177900/35354219-ac4c8cc8-0149-11e8-8c3f-686f76cf94e6.png)


Good luck!

**Comment by cyrinux** [comment]
Thanks you very for those explanations Maxim!

Le mer. 24 janv. 2018 à 21:01, Maxim Baz <notifications@github.com> a
écrit :
