### ISSUE TITLE
some Questions...

### ISSUE THREAD

**Issue by n1ete** [maximbaz/dotfiles#21]
After some excursions into eoli3n's and your dots i decided to switch most of my plans back to your workflow, since its way more efficient and also less prone to errors. i just need to-do some adjustments to the user-setup script so that it fits with stow since i manage my dotfiles already with it.
thanks for the aurutils recommendation. i managed to package my own local repo and it works quite well already.
got some questions and since you support is quite nice i am keen to ask:
1.
could you help me explain a bit more about the "package" workflow you use? 
what are the `"obsolete" "removed" "unknown"` -lists for? they are keeping track of the changes in repo and controlled with repoctl i discovered so far...
right now i sync aur packages with `aur sync -c "$PACKAGENAME"` and  installing them afterward with `paci $PACKAGENAME` finaly pushing changes with `repoctl` to my local or remote repo. 
2.
how do you get the passwords for your mail client into the .cache files? is this managed with pass? or are they just plaintext files?
3.
i have an unconfigured zsh prompt style after zsh folder deployment in `setup-user.sh`  do i miss something to configure or to point at?

thanks again for sharing this with the community!
cheers
n1ete

**Comment by maximbaz** [comment]
Happy to answer 🙂 

1. Package workflow is not ideal, I'll explain what I have now and then some ideas which I have but haven't had time/energy to implement yet.

`"obsolete" "removed" "unknown"` are files which are committed in git repo as empty, they are being updated with the `backup-packages` script that runs periodically, and in ideal world they should always be empty, so when they are not, it's an indicator for me that I must do some cleanup. My workflow is the following, when I `cd ~/.dotfiles` and run `git diff`, if I see changes in one of these three files, it means I must update my metapackage.

- `removed` means that I removed a package that is still listed as a dependency of my `maximbaz` metapackage. To give you an example, say I was using `chromium` (and it was listed in PKGBUILD of my metapackage), and then I switched to `qutebrowser` and I no longer use chromium. If I try to delete it using `pacr chromium`, `pacman` would refuse this removal operation, because chromium is a dependency of my metapackage. A _proper_ way would be to go, update PKGBUILD of my metapackage, rebuild it, install new version, and then go back to removing `chromium`. But it's too much! So my lazy and not-so-good approach is to use `pacr!`, which forces `pacman` to remove `chromium` regardless of it being a dependency. But not to forget and to eventually update my PKGBUILD, the `backup-packages` script will add `chromium` to the `removed.list` file.
- `obsolete` contains all packages that used to be dependencies of some other package, but not anymore. This can happen with official packages, and _most probably_ these can be safely removed (but I like to look at them and remove manually). In addition to that, with my workflow a package can enter `obsolete` if e.g. I remove `chromium` from PKGBUILD of my metapackage, but I forget to remove the `chromium` package itself, so it will be there as a reminder.
- `unknown` is a list of packages that are explicitly installed on my system, instead of being part of PKGBUILD of my metapackage. Most commonly this happens if I install some tool via `paci`, so `backup-packages` script will add it to the `unknown.list` and later I will decide what to do, remove this tool if I no longer need it, or add to PKGBUILD.

Basically, as you can see I prefer to use pacman directly in my daily life, not to bother too much with my metapackage, but from time to time cleanup and update my metapackage PKGBUILD with all the changes that I made recently. So these 3 files are sort of a TODO for me.

2. Very good point. Right now they are plaintext files. I'm not sure how to handle this best, maybe you can suggest something? They are not part of my regular `pass`, because it is only linked to my yubikey which requires a touch to get the password, so not suitable for automated mail sync. I could have created a separate password store, with a separate PGP key that has no keyphrase, so that scripts can automatically fetch my mail in background.... But I'm not sure if it has any benefits, my disk is encrypted with LUKS anyway, and if I manage to run a malicious script, it can just as well execute `pass mailpassword` as read that file directly... 

3. Hmmm... Did you initialize all git submodules? zsh prompt theme along with many packages are managed by git submodules. For example, `.zshrc` loads it using `~/.zsh-plugins/powerlevel10k/powerlevel10k.zsh-theme`

**Comment by n1ete** [comment]
1.thanks, that cleared it up!
2. i think integration with pass would be nice so maybee an `PassCmd pass Email/accountname` is already enough, will try it out soon.
3. is fixed just the p10k submodule was missing in `.gitmodules`

**Comment by maximbaz** [comment]
> i think integration with pass would be nice so maybee an PassCmd pass Email/accountname is already enough, will try it out soon. EDIT= ops, missed that you tried that already....

Yeah exactly, it is possible, question is if it brings any value or just gives us fake sense of extra security 😉

**Comment by n1ete** [comment]
since it doesnt hurt, i go with an file for my email passwords that i encrypt with an separate gpg keypair for now until i can put some more time into this.
since your one of the nnn devs, can you give some hints for good workflows with it? the featurelist is simply amazing. 

yet i feel a bit lost for now andt reminds me kinda of my first vim attempts..... :D 

tried to access an android device via mtp and mounting nfs/smb/s3/local shares for instance... without success so far..

thanks again for your time and help ;)

**Comment by maximbaz** [comment]
To be honest I think my `nnn` workflows are very basic 😄 I use multiple contexts `[1-4]` to select stuff in one place and move it to another, `ctrl+n` mode to quickly navigate, filter mode (e.g. to remove all `.txt` files press `/.txt<esc>ax`, provides sort of kakoune-like way of working where you first make visual selection and then apply operation) and batch rename 🙂 

I did try an sshfs mount a few times which worked fine for me, but haven't had a need to use it often...

I'm not very involved in nnn development these days, so if you find some issues or questions with nnn specifically, I would suggest just opening an issue in that repo to get a faster response (although perhaps not always satisfactory... 😄)

**Comment by n1ete** [comment]
i finally got grip on nnn, thanks again for your time and explanations ;)
