### ISSUE TITLE
systemd: (sway|wayland)-session.target vs ConditionEnvironment

### ISSUE THREAD

**Issue by maximbaz** [maximbaz/dotfiles#23]
I would like to follow-up on https://github.com/emersion/mako/pull/293 and https://github.com/swaywm/sway/issues/5160 to better understand different approaches for configuring systemd services for Wayland apps. I hope you guys don't mind a ping and answering some questions! 🙂 

The task is: make sure a systemd service is started only in a graphical Wayland session (applies to e.g. waybar or mako).

As far as I understand, there are two main competitive alternatives:

1. Introduce a `(sway|wayland)-session.target` and let services be `WantedBy` them
1. Use standard `WantedBy=graphical-session.target` and additionally require that Wayland is running using `ConditionEnvironment=WAYLAND_DISPLAY` or similar.

@gdamjan you wrote on [sway wiki](https://github.com/swaywm/sway/wiki/Systemd-integration) how to create a `sway-session.target` by hand, to support the first scenario. You also contributed [waybar.service](https://github.com/Alexays/Waybar/blob/master/resources/waybar.service.in) which follows the same approach, although that one uses `wayland-session.target` instead.

@xdbob you tried to get `wayland-session.target` [merged into systemd itself](https://github.com/systemd/systemd/pull/15180), but the conclusion of that PR was that it should be a condition instead, so the second approach from the above. As far as I understand from [this note](https://github.com/xdbob/sway-services/issues/12), you want to update all your services to follow this convention now.

@WhyNotHugo you seem to be using the combination of both approaches, you [created `sway-session.target`](https://github.com/WhyNotHugo/dotfiles/blob/master/home/.config/systemd/user/sway-session.target) but in [mako.service](https://github.com/emersion/mako/blob/master/contrib/systemd/mako.service.in) you chose to depend on the standard `graphical-session.target` and instead use the `Condition` option.

Yet another approach is not to declare any extra condition, for example [dunst.service](https://github.com/dunst-project/dunst/blob/master/dunst.systemd.service.in) does not specify any condition to ensure it can only run on X11. However as I understand, a condition is really beneficial for people who often switch between X11 and Wayland, which seems to be particularly popular among Gnome people.

-----

I understand there is a lot of history, but do you guys think we could try to converge on a single conventional way now?

For example, given that `(sway|wayland)-session.target` will not be merged in systemd, shall we stop using them?

In that case, would it be best to have the following in the bottom of sway config?

```
exec "systemctl --user import-environment; systemctl --user start graphical-session.target"
```

Do we also acknowledge that the `ConditionEnvironment=WAYLAND_DISPLAY` is indeed beneficial to have, despite the fact that other software (like dunst) doesn't have it?

Looking forward to your thoughts 🙂

**Comment by WhyNotHugo** [comment]
Regarding `(sway|wayland)-session.target`: I've mostly seen this pushed by people who want their system to be able to boot into Xorg or Wayland. Or people who have both installed, want to support both being available, etc. This is especially true of `wayland-session.target`, since they take `graphical-session` as a synonym for X11-session.

Personally, I only have _one_ desktop available, so I stick to the standard `graphical-session.target`. It's standard, and part of systemd. I'd rather not diverge from upstream unless I need to. The more I avoid diverging, the easier it is to learn/share with others.

[In my case] `sway-session.target` is started explicitly by `sway`, which means sway is fully up (this means not only wayland, but `sway`'s IPC too, which waybar relies on). `graphical-session.target` _may_ be started earlier if you use a login manager or greeter of whatever. I'm not 100% sure though, I don't use one. To me, personally, there's no real difference.

Something that _really_ pissed me, is that things like Waybar [depend on a nonexistent target](https://github.com/Alexays/Waybar/blob/master/resources/waybar.service.in). This means I don't need to have a `service` file for it in my dotfiles, but I _do_ need an extra `target` file, which is kinda the same. :facepalm: 

My [`sway-session.target`](https://github.com/WhyNotHugo/dotfiles/blob/master/home/.config/systemd/user/sway-session.target) is literally a copy-paste of [the one in the wiki](https://github.com/swaywm/sway/wiki/Systemd-integration). It works perfectly. I wish upstream would just include the file itself (I've though of a PR, but I don't have the time for the discussion it might spark).

I don't use `Condition` anywhere, it's an ugly hack. It's used in mako because apparently many people wanted to install `mako`, but use `X11`, so the DBus activation messed things up for them. It's really only needed if you have a DBus-activated Wayland-only service and run X11 (or the other way around).

> Yet another approach is not to declare any extra condition, for example dunst.service does not specify any condition to ensure it can only run on X11. However as I understand, a condition is really beneficial for people who often switch between X11 and Wayland, which seems to be particularly popular among Gnome people.

100% correct. Again, I don't keep X11-related services installed, so they're never a problem for me. If you installed Dunst and ran Wayland, it might get picked up by dbus-activation.

See also https://github.com/swaywm/sway/issues/5160

---

Honestly, it's come to this mess because so many people want so many different things. I try to keep it simple, and just have sway installed, but some seem to need having multiple compositors and/or Xorg WMs, and want a single setup where they're capable of running any of them (and even one nested inside the other), each with their own services. It's hard to fix anything without it breaking for _someone_.

**Comment by maximbaz** [comment]
Thanks for the detailed response!

> Regarding `(sway|wayland)-session.target`: I've mostly seen this pushed by people who want their system to be able to boot into Xorg or Wayland.

Now that we know that systemd [will not include such targets](https://github.com/systemd/systemd/pull/15180), it seems rational to stop using them now. @gdamjan would love to hear your opinion in particular on this as you wrote the sway wiki page.

> Something that really pissed me, is that things like Waybar depend on a nonexistent target. This means I don't need to have a service file for it in my dotfiles, but I do need an extra target file, which is kinda the same. 🤦

I completely agree, it doesn't help when third-party services depend on non-existent targets, in particular services that are not automatically activated by DBUS.

Waybar service needs to be `enabled` first anyway, so there is really no need to add extra `Condition`s or especially depend on non-standard targets. People who use Wayland exclusively will enable `waybar.service`, people who need it on demand can just start the service from sway config.

Again, @gdamjan would love to hear your thoughts here as you contributed `waybar.service`.

> [In my case] sway-session.target is started explicitly by sway, which means sway is fully up (this means not only wayland, but sway's IPC too, which waybar relies on). `graphical-session.target` may be started earlier if you use a login manager or greeter of whatever. I'm not 100% sure though, I don't use one.

This is an interesting idea, but if that's the case, I would assume the login managers need to be improved not to launch `graphical-session.target` too soon.

If that's not the case, then it sounds like we could just start `graphical-session.target` from our sway configs, a standard target that does not need to be included in the sway codebase?

**Comment by WhyNotHugo** [comment]
> I would assume the login managers need to be improved not to launch `graphical-session.target` too soon.

Too many people on too many large project need to agree on that. I'd take these things as they are, and not consider them changeable in the short term.

I might have been mistaken in my assumption though, that's something that needs further research. I've no idea how those work.

> If that's not the case, then it sounds like we could just start graphical-session.target from our sway configs, a standard target that does not need to be included in the sway codebase?

This will break stuff for people who have coexisting X11 and Wayland setups. It'd be hard to push that change on all projects. Anything that's standardised across all projects needs to consider these users, or the changes will end up getting rejected.

**Comment by maximbaz** [comment]
Some things I've learned today:

- `graphical-session.target` is an ["dynamic alias"](https://github.com/systemd/systemd/commit/c92fcc4f4375b0), not meant to be started directly (and not possible to do so). So creating and later starting `sway-session.target` is really the only correct way, we are doing the right thing. I agree with what you said earlier, that technically sway should provide `sway-session.target`.
- No service should require custom non-standard targets, that was the whole purpose for `graphical-session.target` to be created, so that services are usable for everyone regardless of what WMs they are using, people should not be expected to create and start additional targets only to satisfy some service unit. I agree that waybar is not doing the right thing currently.
- If you ever exit sway using `swaymsg exit`, you should remember to stop `sway-session.target`, so that all services that require display can exit properly.

In fact starting, stopping and starting sway again (including its target) is a great way to catch services that are misconfigured, they would either not start, not exit correctly or just crash because display disappeared.

I feel optimistic to try submitting a couple of PRs to try to improve some services, will see how it goes 🙂

**Comment by WhyNotHugo** [comment]
> graphical-session.target is an "dynamic alias", not meant to be started directly (and not possible to do so). So creating and later starting sway-session.target is really the only correct way, we are doing the right thing. I agree with what you said earlier, that technically sway should provide sway-session.target.

I wish they'd document this beyond a commit message. :disappointed: 

You might want to mention this in the relevant sway wiki article. With this as an upstream source, it might make sense to push a PR to sway and start trying to push for it to happen.

> No service should require custom non-standard targets, that was the whole purpose for graphical-session.target to be created, so that services are usable for everyone regardless of what WMs they are using, people should not be expected to create and start additional targets only to satisfy some service unit. I agree that waybar is not doing the right thing currently.

`waybar` is a notable exception because it doesn't start "when wayland is up", is starts when **"sway"** is up. It explicitly relies on `sway` since it uses its IPC. It _should_ depend on `sway-session.target` (or whatever `sway` end up providing). It should probably `BindTo` as well.

**Comment by maximbaz** [comment]
> You might want to mention this in the relevant sway wiki article. With this as an upstream source, it might make sense to push a PR to sway and start trying to push for it to happen.

👍 

> waybar is a notable exception because it doesn't start "when wayland is up", is starts when "sway" is up. It explicitly relies on sway since it uses its IPC.

I would bring the following arguments for arguing against this ( 🙂 ):

- Waybar works with all wlroots-based compositors, not only with sway 
- It only needs sway IPC for a subset of its modules (for example I dont use any of those modules)

With that in mind, I would think that approach that is most useful for the majority of people would be to change waybar to depend on `graphical-session.target` (so that it works out of the box for folks using e.g. Wayfire and both of us, who start `sway-session.target` in the appropriate time)

And only if you spot that your login manager starts `graphical-session.target` before it actually starts the... hm, the process responsible for graphical session (sway)... and only if you actually use modules that rely on the IPC, then you go and create your custom `waybar.service` that binds to a custom target that you yourself start at the appropriate time.

Does this sound reasonable to you? 🙂

**Comment by WhyNotHugo** [comment]
> It only needs sway IPC for a subset of its modules (for example I dont use any of those modules)

Fair, but you want something that works for everyone, otherwise up-streaming it isn't gonna work.

> And only if you spot that your login manager starts...

I don't use one, so can't provide adequate feedback, sorry. All I can say is, input is missing here before being certain.

**Comment by gdamjan** [comment]
> I would assume the login managers need to be improved not to launch graphical-session.target too soon.

login managers don't launch graphical-session.target, sway.service needs to launch it by having Before=graphical-session.target and BindsTo=graphical-session.target

**Comment by maximbaz** [comment]
Thanks for all your answers, I think I got all the uncertainties clarified now. 

PR for adding `sway-session.target`: https://github.com/swaywm/sway/pull/5622
