### ISSUE TITLE
kakoune socket sometimes owned by root?

### ISSUE THREAD

**Issue by n1ete** [maximbaz/dotfiles#25]
it happens occasionally that the kakoune socket folder `/run/user/1000/kakoune` is owned by 'root' insted of 'user'.
a simple `$ sudo chown n1ete:n1ete /run/user/1000/kakoune` fixes it and usuallly it stays that way for quite a time... i couldnt find any reason yet what could cause this...

thanks again for your awesome projects and support!

**Comment by maximbaz** [comment]
Yes I know what you are talking about, this annoys me as well! 

I believe the reason is that on the _very first time_ after boot, when you open `kak` for the first time, it will create `/run/user/1000/kakoune` folder, and if this very first time if you ran kakoune as root user (with sudo, or in `sudo -s` shell), then that `/run/user/1000/kakoune` is going to be owned by root, and so if you open kakoune next time as a normal user, it will not have permissions to read this folder anymore.

I haven't looked in detail whose problem it is exactly, is it kakoune that must be fixed, or who... But I agree, lets solve this once and for all. A silly "workaround" in the meantime is just to open and close kakoune after a fresh boot...
