### ISSUE TITLE
Kakoune does not work correctly anymore

### ISSUE THREAD

**Issue by kratnor** [maximbaz/dotfiles#28]
Hi,
after an update of your dotfiles, a lot of kakoune does not work correctly anymore:
User mappings: buffers, files, new terminal

Is it broken for you as well or did I do a mistake?

**Comment by maximbaz** [comment]
Hey! It's not broken for me, first idea: try running `gsu`, in case you have old submodules (`git submodule update --remote`).

If this fails, open kakoune, press `:o *debug*` and post here the output, it will give us a hint 🙂

**Comment by kratnor** [comment]
I updated the submodules, that did not help.
If I start kitty with bash instead of zsh, everything works fine as well.
The debug buffer does not help for files and buffers (kakoune writes: waiting for shell command to finish)
For kitty terminal it simply prints: Error: no such command: 'kitty-terminal'
Even though it is a kakoune built in command.

**Comment by maximbaz** [comment]
Ooooh, I know then - it's caused by us using z4h bleeding-edge v5, we are tracking this issue with kitty in zsh4humans repo. 

The simplest solution I can offer is switch to `v4`, just make two changes in `.zshenv` and open a new terminal and that should solve it.

**Comment by kratnor** [comment]
Good to know, thank you for your help!

**Comment by maximbaz** [comment]
As another alternative, if you want to stay on v5, is to add this line to your .zshrc, but be warned that v5 can be pretty unstable from time to time 😉 

```
zstyle :z4h start-tmux no
```

**Comment by n1ete** [comment]
is it also possible that this has broken gruvbox theme in kakoune and kitty? 
since i commit changes from your repo by hand to learn, its also be possible that i broke something....
and thanks btw for fixing #25 
;)

**Comment by maximbaz** [comment]
> is it also possible that this has broken gruvbox theme in kakoune and kitty?

Yep! This particular issue is fixed in the latest z4h, so if you are using v5, make sure to run `z4h update` very often, bugs are being discovered and fixed very frequently. Or just stay on v4 for now, until v5 gets a bit more stable (it truly is bleeding edge now) 🙂 

For v5, this commit makes sure that colors are correct locally, but on remote (where it's more painful to have a broken terminal) we use z4h's own logic to determine the proper $TERM, which means colors might be off: https://github.com/maximbaz/dotfiles/commit/54b59bf0e599d4c5f1f69980a9c4dbfa1503d000
