### ISSUE TITLE
Do I need to install i3 before using this ?

### ISSUE THREAD

**Issue by steelx** [maximbaz/dotfiles#29]
Hi,

Im new to Linux, do I need to install i3 for using this ? Or I can use it on my existing Manjaro Gnome linux

**Comment by maximbaz** [comment]
Hi, what I would recommend you is not taking this repo entirely as it is, but look and pick only the things that you use or are curious about. For example, if you use neomutt, check out my neomutt config and compare it with yours, and google the difference to understand exactly what those options do - you will learn a lot in the process, you won't have to replace any software in advance, and you will end up with a setup that fits your personal style! 

To answer specifically about DE, I user neither Gnome nor i3, I use sway 🙂 

If you get any questions, do not hesitate to ask 😉

**Comment by steelx** [comment]
@maximbaz thanks for response. I will definitely study as you mentioned. :) 
Actually I wanted to ask if it will allow me to choose a Window Manager during login if Im not able to use Sway.

**Comment by maximbaz** [comment]
I place my bet on the fact that GDM should take care of it since you use Gnome, when you logout and are presented with a user/password prompt, there is a button somewhere that can allow you to choose for example Xorg Gnome vs Wayland Gnome, in that same menu sway should appear once you install it - I think so at least, I haven't actually used Gnome 😄

**Comment by maximbaz** [comment]
Closing but do ping me if you have any other questions 😉
