### ISSUE TITLE
Bug with environment.d

### ISSUE THREAD

**Issue by kratnor** [maximbaz/dotfiles#30]
There seems to be a bug with your way to set environment variables.
For example PASSWORD_STORE_CHARACTER_SET gets resolved like this:
$'a-zA-Z0-9~!@#$%^&*()-_=+[]{};:,.<>?'
instead of this
a-zA-Z0-9~!@#$%^&*()-_=+[]{};:,.<>?

Seems like this method has problems with things like spaces and other special characters.

**Comment by maximbaz** [comment]
Thanks for bringing this to my attention, much appreciated! 👍 

This is [a bug in systemd](https://github.com/systemd/systemd/issues/17340), I subscribed to be notified when it is fixed. In my case the issue is luckily only with `$PASSWORD_STORE_CHARACTER_SET`, which I can survive for now...

**Comment by maximbaz** [comment]
I decided to abandon setting PASSWORD_STORE_CHARACTER_SET altogether, and I don't know if actually setting `home.sessionVariables` with Nix solves this in any case, but after 4 years of this being open, I think it's safe to say the issue is not really significant enough to care about it... :sweat_smile:
