### ISSUE TITLE
Question: Mako mute notifications

### ISSUE THREAD

**Issue by mordax777** [maximbaz/dotfiles#35]
Hello,

Just a few days ago, I was thinking about how to mute Makos notifications, since I don't want to share all my private conversations with everyone while screen sharing :smile:  I saw your previous solution with `makoctl set` and tried it out myself. Found out that it was actually not implemented yet in an official release and not even planned for release because of some issues I believe? However, I just stumbled upon your workaround in https://github.com/maximbaz/dotfiles/commit/a46192806d6f0a2bb6c5031150b59fff53ca0d6a and had a questions.

I added your changes from the commit to my own system, but when I use `systemctl` to check Maco's status, I get:
```
~ 
❯ systemctl --user status mako
Unit mako.service could not be found.

~ 
❯ systemctl status mako
Unit mako.service could not be found.
```
I am not familiar with `dbus-1/services`, so I would need some help understanding what I am doing wrong. :slightly_smiling_face: 

Thanks!

**Comment by maximbaz** [comment]
Hello! 

`makoctl set` was actually implemented for a while in `master` branch, but then got reverted 😞 We are waiting for https://github.com/emersion/mako/issues/335 - see https://github.com/emersion/mako/issues/278#issuecomment-795661822 and https://github.com/emersion/mako/issues/278#issuecomment-799449253

You are doing everything correctly, the issue is that you don't have systemd service because it was only added after the last `mako` release - so it works for me, because I use `AUR/mako-git`.

If you want to keep running `community/mako`, you can simply put [mako.service](https://github.com/emersion/mako/blob/master/contrib/systemd/mako.service) to `~/.config/systemd/user/` folder and `systemctl --user daemon-reload` to get it. Then it should all work, hopefully. 

But I would suggest to consider using `mako-git`, unfortunately they are cutting releases waay to rarely (last one was more than a year ago!).

**Comment by mordax777** [comment]
Ah yes, that fixed it!

I was a bit confused because I saw the package here https://github.com/maximbaz/dotfiles/blob/master/packages/PKGBUILD#L182 and thought it was the `community/mako` one. 

But thanks for your help!
Closing this one. :slightly_smiling_face:
