### ISSUE TITLE
Hyprland Waybar Questions

### ISSUE THREAD

**Issue by kontax** [maximbaz/dotfiles#54]
Hey @maximbaz, 

I've a couple of questions on waybar within your setup if you are able to help?

I finally took the plunge into hyprland, but I'm not sure how you launch waybar, as you removed the systemd service when migrating from sway, and I can't see an exec-once command in your config. How do you start it up?

And secondly, I couldn't get the stock waybar package to work, and had to go with [waybar-hyprland](https://aur.archlinux.org/packages/waybar-hyprland). This differs from what you had in your package list however, so I'm just wondering whether you are having no issues with the stock package?

Thanks in advance.

**Comment by maximbaz** [comment]
Hello! I'm always happy to help out :wink: 

I still launch waybar using systemd service, it is simply being packaged now as part of waybar package itself (installed at `/usr/lib/systemd/user/waybar.service`, you still enable and start it as a user service).

My package list is slightly outdated, sorry about it. You are completely right in going for the `waybar-hyprland`. I'm happy to tell you though that there is now [a ticket to subscribe to](https://github.com/hyprwm/Hyprland/issues/2084), where the discussion has started about implementing the proper protocol, so that this custom patch for waybar would no longer be needed.

Until then, consider using [a better patch](https://github.com/hyprland-community/hyprland-autoname-workspaces/issues/44#issuecomment-1533834100) for waybar, it fixes some issues when using advanced features, like html tags for coloring your workspaces.

**Comment by kontax** [comment]
Ah brilliant, thanks so much for the replies that's very helpful!

**Comment by maximbaz** [comment]
In case you haven't seen, the fix has been implemented in Hyprland, so you need to get the latest hyprland-git, and waybar-git will work without any patches, if you build with `-Dexperimental=true` :wink:

**Comment by kontax** [comment]
I just saw that, thanks for the heads up!
