### ISSUE TITLE
i3status errors

### ISSUE THREAD

**Issue by insuusvenerati** [maximbaz/dotfiles#7]
Hey I love this i3 config and i'm trying to integrate it into my own setup but having an issue with some of the external scripts in i3status. 

The updates ones seem to be having issues. Like this, http://i.imgur.com/tJbvBvP.png

It seems to use aurutils which i have installed but i'm not sure which additional component i'm missing. Would you mind helping me out?

**Comment by maximbaz** [comment]
Hey there 🙂 

The `need_rebuild` one I'm currently developing, just disable it from your `.i3status.conf` for now — I can ping you when it's ready, I'm hopefully done with it in the next few days.

The rest of them are red because `~/bin` folder is not in your `$PATH`, this config:

https://github.com/maximbaz/dotfiles/blob/f3323770b44a5fbe14e807dbb1a42a17d9e3884c/etc/profile.d/zz_custom.sh#L18-L19

Keep in mind that this is `profile.d` config, so you need to reboot for it to take effect.

**Comment by insuusvenerati** [comment]
Awesome thanks! I can add the bin folder to my dotfiles and setup a path.zsh that'll get run with a custom update function so it gets added to my path automatically.

**Comment by maximbaz** [comment]
@insuusvenerati I released [rebuild-detector](https://aur.archlinux.org/packages/rebuild-detector/) on AUR, it provides the script `checkrebuild` which will tell you which packages are broken and need to be rebuilt. First of all, it is only relevant for Arch Linux, so if you are on different OS, just remove that section from i3status 🙂  If you are on Arch and use aurutils, you can additionally filter the packages by repo (like I do), this removes false positives.

See also: https://github.com/maximbaz/dotfiles/commit/77205c8573a536514fc463ee3ec1b28c76cf83a9
